fix: mobileVisibleFields signature (#1058)
The error leaks in downstream projects with stricter typechecking
settings:

```
❯ pnpm run type-check

> udata-front-kit@0.4.0 type-check /Users/alexandre/Developer/Ecolab/Ecopshères/ecospheres-front
> vue-tsc --noEmit --project tsconfig.app.json

node_modules/@datagouv/components-next/src/components/TabularExplorer/TabularExplorer.vue:754:30 - error TS6133: 'row' is declared but its value is never read.

754 function mobileVisibleFields(row: TabularRow, index: number): string[] {
                                 ~~~


Found 1 error in node_modules/@datagouv/components-next/src/components/TabularExplorer/TabularExplorer.vue:754

 ELIFECYCLE  Command failed with exit code 1.
```